name: CI - Test OCR-Parse-AI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Playwright Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./client

      - name: Run Playwright tests
        run: npx playwright test
